import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import InboxSidebar from "@/components/inbox-sidebar"; // New component for the sidebar

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <fieldset className="border border-solid border-1 border-slate-700 p-4">
          <legend>/app/layout.tsx</legend>
          <div className="flex">
            <InboxSidebar />
            <div className="flex-1 flex">{children}</div>
          </div>
        </fieldset>
      </body>
    </html>
  );
}
